### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by matkoniecz** [MattiaCinelli/notebooks#1]
See https://choosealicense.com/ for tl;dr and to confirmation that it is a real problem

Currently no license is mentioned anywhere, what makes this code fully copyrighted. This is a default for any creative work - what includes software.

Please, please add a license. The fact none is listed makes using this software a legal quagmire.

For start - people are not allowed to make own program based on examples you published - as it is fully copyrighted.

Hopefully this is not the intended effect, given that code was open sourced and published as a tutorial .

In case that for some reason not releasing it under open license is intentional - mentioning it in the readme also would be a good idea. Though note that given that it is open sourced it will not stop anyone not caring about copyrights.

Popular licences include:

 - MIT license that allows people to use code for any purpose
 - GNU GPLv3 that intends to allow everything but to block people from distributing closed source versions that build on open source project

Feel free to ask me questions :) I know and understand that people often prefer to ignore copyright law, unfortunately it will not make it disappear.

**Comment by matkoniecz** [comment]
In my specific case I wanted to use https://medium.com/analytics-vidhya/how-to-do-a-sankey-plot-in-python-5298869f5e8e tutorial code but now I will need to do in some way that will be sufficiently distinct from reusing tutorial code to be copyright-safe.

**Comment by MattiaCinelli** [comment]
Done added MIT License
